### ISSUE TITLE
Continue playing secton is broken

### ISSUE THREAD

**Issue by G4M3R1233** [tersiswilvin/Roblox-2019-Old-Theme#82] opened 2024-07-30 00:15 UTC
### Are you up-to-date?

- [X] I've confirmed that I am completely up-to-date.

### Is the problem in Experimental?

- [X] I've verified that the problem persists in the Experimental Branch.

### Browser

Firefox

### Page URL

https://www.roblox.com/discover#/sortName/v2/Continue

### Channel

Experimental

### Type

CSS

### Describe the Problem

The discover page is bugged? Any solutions to fix the issue
![Screenshot (405)](https://github.com/user-attachments/assets/328f17cb-3a64-451e-a043-573020fdf9fc)

**Comment by tersiswilvin** [comment] 2024-07-30 00:26
Cannot replicate in experimental.
![image](https://github.com/user-attachments/assets/97a21b88-b8b5-4bf9-94c9-0472da261e7a)

**Comment by tersiswilvin** [comment] 2024-07-30 00:29
Appears to be duplicate of https://github.com/tersiswilvin/Roblox-2019-Old-Theme/issues/79 which was fixed in https://github.com/tersiswilvin/Roblox-2019-Old-Theme/commit/e2926871886777d6e2277dcd12c0f890f2fb0e96

**Closed as completed** 2024-07-31 00:52 UTC
Labels: bug
