### ISSUE TITLE
pre 2018 should have bars instead of %

### ISSUE THREAD

**Issue by assholegaming29** [tersiswilvin/Roblox-2019-Old-Theme#57] opened 2024-04-29 08:13 UTC
### Type

CSS

### Describe the Feature

this picture of the game page had bars instead of %
but sadly you cant really replicate it so just hide it and just make the bar full
aslo FIX OBC THEME some parts are UNREADABLE
![image](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/156504697/33d43512-6a50-4c7c-bdfd-ed11e80c9148)

**Comment by mx-mic** [comment] 2024-04-29 09:02
This was suggested in an earlier issue (#12). It would most likely be replicable with JS however @tersiswilvin is working on other things to make the theme more compatible with the massive wave of Roblox A/B tests coming in at the moment.

**Comment by tersiswilvin** [comment] 2024-05-05 13:35
Duplicate of #12

**Closed by tersiswilvin** 2024-05-05 13:35 UTC
Labels: enhancement
