### ISSUE TITLE
home page broken

### ISSUE THREAD

**Issue by dudeman349** [tersiswilvin/Roblox-2019-Old-Theme#55] opened 2024-04-13 16:48 UTC
### Are you up-to-date?

- [X] I've confirmed that I am completely up-to-date.

### Is the problem in Experimental?

- [X] I've verified that the problem persists in the Experimental Branch.

### Browser

Google Chrome

### Page URL

https://www.roblox.com/home

### Channel

Release

### Type

CSS

### Describe the Problem

![image](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/125472062/4f9fcff9-ccef-4343-ab3b-5db9ab57c474)
![image (68)](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/125472062/46a98a58-1c3a-44fa-b839-0d87356b2aed)

**Comment by tersiswilvin** [comment] 2024-04-15 00:35
I've already been aware of this issue, however with multiple different roblox home pages roblox is currently testing at the moment it is currently difficult to add support to 3 different a/b testing versions (especially V1 and V2 with the structure being similar but different enough that any fixes from V1 breaks V2 or V2 fixes break V1), I am in the process of waiting to see which version gets fully released so I can integrate the appropriate fix for it.

**Comment by tersiswilvin** [comment] 2024-05-05 13:31
> I've already been aware of this issue, however with multiple different roblox home pages roblox is currently testing at the moment it is currently difficult to add support to 3 different a/b testing versions (especially V1 and V2 with the structure being similar but different enough that any fixes from V1 breaks V2 or V2 fixes break V1), I am in the process of waiting to see which version gets fully released so I can integrate the appropriate fix for it.

Implimented A/B homepage version, however roblox currently has around 4 to 5 A/B homepage layouts being given at this time, I currently only have access to 3 of the 4/5 roblox has.

**Comment by tersiswilvin** [comment] 2024-05-05 13:33
Duplicate of #54.

**Closed as completed by tersiswilvin** 2024-05-05 13:33 UTC
Labels: bug
