### ISSUE TITLE
Large empty space to side of screen

### ISSUE THREAD

**Issue by drinkcept** [tersiswilvin/Roblox-2019-Old-Theme#94] opened 2024-08-29 19:53 UTC
### Are you up-to-date?

- [X] I've confirmed that I am completely up-to-date.

### Is the problem in Experimental?

- [X] I've verified that the problem persists in the Experimental Branch.

### Browser

Firefox

### Page URL

https://www.roblox.com/home

### Channel

Release

### Type

CSS

### Describe the Problem

![image](https://github.com/user-attachments/assets/fea7bb1f-ae68-4c74-9eac-f3bb6cdd6f78)

**Comment by tersiswilvin** [comment] 2024-08-30 19:12
Duplicate of https://github.com/tersiswilvin/Roblox-Legacy-Old-Theme/issues/78.

**Closed as not planned by tersiswilvin** 2024-08-30 19:12 UTC
Labels: bug
